import { KeybLayout } from './types'

export const fullSize: KeybLayout = {
  name: '100% Full Size',
  width: 1050,
  height: 320,
  rows: [
    [
      { label: 'Esc', code: 'Escape', width: 40, height: 40, color: 'orange' },
      { label: 'F1', code: 'F1', width: 40, height: 40 },
      { label: 'F2', code: 'F2', width: 40, height: 40 },
      { label: 'F3', code: 'F3', width: 40, height: 40 },
      { label: 'F4', code: 'F4', width: 40, height: 40 },
      { label: 'F5', code: 'F5', width: 40, height: 40 },
      { label: 'F6', code: 'F6', width: 40, height: 40 },
      { label: 'F7', code: 'F7', width: 40, height: 40 },
      { label: 'F8', code: 'F8', width: 40,  height: 40 },
      { label: 'F9', code: 'F9', width: 40, height: 40 },
      { label: 'F10', code: 'F10', width: 40, height: 40 },
      { label: 'F11', code: 'F11', width: 40, height: 40 },
      { label: 'F12', code: 'F12', width: 40, height: 40 },
      { label: 'PrtSc', code: 'PrintScreen', width: 40, height: 40 },
      { label: 'ScrLk', code: 'ScrollLock', width: 40, height: 40 },
      { label: 'Pause', code: 'Pause', width: 40, height: 40 },
    ],
    [
      { label: '`', code: 'Backquote', width: 40, height: 40 },
      { label: '1', code: 'Digit1', width: 40, height: 40 },
      { label: '2', code: 'Digit2', width: 40, height: 40 },
      { label: '3', code: 'Digit3', width: 40, height: 40 },
      { label: '4', code: 'Digit4', width: 40, height: 40 },
      { label: '5', code: 'Digit5', width: 40, height: 40 },
      { label: '6', code: 'Digit6', width: 40, height: 40 },
      { label: '7', code: 'Digit7', width: 40, height: 40 },
      { label: '8', code: 'Digit8', width: 40, height: 40 },
      { label: '9', code: 'Digit9', width: 40, height: 40 },
      { label: '0', code: 'Digit0', width: 40, height: 40 },
      { label: '-', code: 'Minus', width: 40, height: 40 },
      { label: '=', code: 'Equal', width: 40, height: 40 },
      { label: 'Backspace', code: 'Backspace', width: 80, height: 40 },
      { label: 'Ins', code: 'Insert', width: 40, height: 40 },
      { label: 'Home', code: 'Home', width: 40, height: 40 },
      { label: 'PgUp', code: 'PageUp', width: 40, height: 40 },
      { label: 'Num', code: 'NumLock', width: 40, height: 40 },
      { label: '/', code: 'NumpadDivide', width: 40, height: 40 },
      { label: '*', code: 'NumpadMultiply', width: 40, height: 40 },
      { label: '-', code: 'NumpadSubtract', width: 40, height: 40 },
    ],
    [
      { label: 'Tab', code: 'Tab', width: 60, height: 40 },
      { label: 'Q', code: 'KeyQ', width: 40, height: 40 },
      { label: 'W', code: 'KeyW', width: 40, height: 40 },
      { label: 'E', code: 'KeyE', width: 40, height: 40 },
      { label: 'R', code: 'KeyR', width: 40, height: 40 },
      { label: 'T', code: 'KeyT', width: 40, height: 40 },
      { label: 'Y', code: 'KeyY', width: 40, height: 40 },
      { label: 'U', code: 'KeyU', width: 40, height: 40 },
      { label: 'I', code: 'KeyI', width: 40, height: 40 },
      { label: 'O', code: 'KeyO', width: 40, height: 40 },
      { label: 'P', code: 'KeyP', width: 40, height: 40 },
      { label: '[', code: 'BracketLeft', width: 40, height: 40 },
      { label: ']', code: 'BracketRight', width: 40, height: 40 },
      { label: '\\', code: 'Backslash', width: 60, height: 40 },
      { label: 'Del', code: 'Delete', width: 40, height: 40 },
      { label: 'End', code: 'End', width: 40, height: 40 },
      { label: 'PgDn', code: 'PageDown', width: 40, height: 40 },
      { label: '7', code: 'Numpad7', width: 40, height: 40 },
      { label: '8', code: 'Numpad8', width: 40, height: 40 },
      { label: '9', code: 'Numpad9', width: 40, height: 40 },
      { label: '+', code: 'NumpadAdd', width: 40, height: 80 },
    ],
    [
      { label: 'Caps', code: 'CapsLock', width: 80, height: 40 },
      { label: 'A', code: 'KeyA', width: 40, height: 40 },
      { label: 'S', code: 'KeyS', width: 40, height: 40 },
      { label: 'D', code: 'KeyD', width: 40, height: 40 },
      { label: 'F', code: 'KeyF', width: 40, height: 40 },
      { label: 'G', code: 'KeyG', width: 40, height: 40 },
      { label: 'H', code: 'KeyH', width: 40, height: 40 },
      { label: 'J', code: 'KeyJ', width: 40, height: 40 },
      { label: 'K', code: 'KeyK', width: 40, height: 40 },
      { label: 'L', code: 'KeyL', width: 40, height: 40 },
      { label: ';', code: 'Semicolon', width: 40, height: 40 },
      { label: "'", code: 'Quote', width: 40, height: 40 },
      { label: 'Enter', code: 'Enter', width: 80, height: 40 },
      { label: '4', code: 'Numpad4', width: 40, height: 40 },
      { label: '5', code: 'Numpad5', width: 40, height: 40 },
      { label: '6', code: 'Numpad6', width: 40, height: 40 },
    ],
    [
      { label: 'Shift', code: 'ShiftLeft', width: 100, height: 40 },
      { label: 'Z', code: 'KeyZ', width: 40, height: 40 },
      { label: 'X', code: 'KeyX', width: 40, height: 40 },
      { label: 'C', code: 'KeyC', width: 40, height: 40 },
      { label: 'V', code: 'KeyV', width: 40, height: 40 },
      { label: 'B', code: 'KeyB', width: 40, height: 40 },
      { label: 'N', code: 'KeyN', width: 40, height: 40 },
      { label: 'M', code: 'KeyM', width: 40, height: 40 },
      { label: ',', code: 'Comma', width: 40, height: 40 },
      { label: '.', code: 'Period', width: 40, height: 40 },
      { label: '/', code: 'Slash', width: 40, height: 40 },
      { label: 'Shift', code: 'ShiftRight', width: 100, height: 40 },
      { label: '↑', code: 'ArrowUp', width: 40, height: 40 },
      { label: '1', code: 'Numpad1', width: 40, height: 40 },
      { label: '2', code: 'Numpad2', width: 40, height: 40 },
      { label: '3', code: 'Numpad3', width: 40, height: 40 },
      { label: 'Enter', code: 'NumpadEnter', width: 40, height: 80 },
    ],
    [
      { label: 'Ctrl', code: 'ControlLeft', width: 60, height: 40 },
      { label: 'Win', code: 'MetaLeft', width: 60, height: 40 },
      { label: 'Alt', code: 'AltLeft', width: 60, height: 40 },
      { label: 'Space', code: 'Space', width: 60, height: 40 },
      { label: 'Alt', code: 'AltRight', width: 60, height: 40 },
      { label: 'Win', code: 'MetaRight', width: 60, height: 40 },
      { label: 'Menu', code: 'ContextMenu', width: 60, height: 40 },
      { label: 'Ctrl', code: 'ControlRight', width: 60, height: 40 },
      { label: '←', code: 'ArrowLeft', width: 40, height: 40 },
      { label: '↓', code: 'ArrowDown', width: 40, height: 40 },
      { label: '→', code: 'ArrowRight', width: 40, height: 40 },
      { label: '0', code: 'Numpad0', width: 40, height: 80 },
      { label: '.', code: 'NumpadDecimal', width: 40, height: 40 },
    ],
  ],
}

export const compact1800: KeybLayout = {
  name: '1800 Compact',
  width: 1000,
  height: 320,
  rows: [
    [
      { label: 'Esc', code: 'Escape', width: 40, height: 40, color: 'orange' },
      { label: 'F1', code: 'F1', width: 40, height: 40 },
      { label: 'F2', code: 'F2', width: 40, height: 40 },
      { label: 'F3', code: 'F3', width: 40, height: 40 },
      { label: 'F4', code: 'F4', width: 40, height: 40 },
      { label: 'F5', code: 'F5', width: 40, height: 40 },
      { label: 'F6', code: 'F6', width: 40, height: 40 },
      { label: 'F7', code: 'F7', width: 40, height: 40 },
      { label: 'F8', code: 'F8', width: 40, height: 40 },
      { label: 'F9', code:  'F9', width: 40, height: 40 },
      { label: 'F10', code: 'F10', width: 40, height: 40 },
      { label: 'F11', code: 'F11', width: 40, height: 40 },
      { label: 'F12', code: 'F12', width: 40, height: 40 },
      { label: 'Del', code: 'Delete', width: 40, height: 40 },
    ],
    [
      { label: '`', code: 'Backquote', width: 40, height: 40 },
      { label: '1', code: 'Digit1', width: 40, height: 40 },
      { label: '2', code: 'Digit2', width: 40, height: 40 },
      { label: '3', code: 'Digit3', width: 40, height: 40 },
      { label: '4', code: 'Digit4', width: 40, height: 40 },
      { label: '5', code: 'Digit5', width: 40, height: 40 },
      { label: '6', code: 'Digit6', width: 40, height: 40 },
      { label: '7', code: 'Digit7', width: 40, height: 40 },
      { label: '8', code: 'Digit8', width: 40, height: 40 },
      { label: '9', code: 'Digit9', width: 40, height: 40 },
      { label: '0', code: 'Digit0', width: 40, height: 40 },
      { label: '-', code: 'Minus', width: 40, height: 40 },
      { label: '=', code: 'Equal', width: 40, height: 40 },
      { label: 'Backspace', code: 'Backspace', width: 80, height: 40 },
      { label: 'Num', code: 'NumLock', width: 40, height: 40 },
      { label: '/', code: 'NumpadDivide', width: 40, height: 40 },
      { label: '*', code: 'NumpadMultiply', width: 40, height: 40 },
      { label: '-', code: 'NumpadSubtract', width: 40, height: 40 },
    ],
    [
      { label: 'Tab', code: 'Tab', width: 60, height: 40 },
      { label: 'Q', code: 'KeyQ', width: 40, height: 40 },
      { label: 'W', code: 'KeyW', width: 40, height: 40 },
      { label: 'E', code: 'KeyE', width: 40, height: 40 },
      { label: 'R', code: 'KeyR', width: 40, height: 40 },
      { label: 'T', code: 'KeyT', width: 40, height: 40 },
      { label: 'Y', code: 'KeyY', width: 40, height: 40 },
      { label: 'U', code: 'KeyU', width: 40, height: 40 },
      { label: 'I', code: 'KeyI', width: 40, height: 40 },
      { label: 'O', code: 'KeyO', width: 40, height: 40 },
      { label: 'P', code: 'KeyP', width: 40, height: 40 },
      { label: '[', code: 'BracketLeft', width: 40, height: 40 },
      { label: ']', code: 'BracketRight', width: 40, height: 40 },
      { label: '\\', code: 'Backslash', width: 60, height: 40 },
      { label: '7', code: 'Numpad7', width: 40, height: 40 },
      { label: '8', code: 'Numpad8', width: 40, height: 40 },
      { label: '9', code: 'Numpad9', width: 40, height: 40 },
      { label: '+', code: 'NumpadAdd', width: 40, height: 80 },
    ],
    [
      { label: 'Caps', code: 'CapsLock', width: 80, height: 40 },
      { label: 'A', code: 'KeyA', width: 40, height: 40 },
      { label: 'S', code: 'KeyS', width: 40, height: 40 },
      { label: 'D', code: 'KeyD', width: 40, height: 40 },
      { label: 'F', code: 'KeyF', width: 40, height: 40 },
      { label: 'G', code: 'KeyG', width: 40, height: 40 },
      { label: 'H', code: 'KeyH', width: 40, height: 40 },
      { label: 'J', code: 'KeyJ', width: 40, height: 40 },
      { label: 'K', code: 'KeyK', width: 40, height: 40 },
      { label: 'L', code: 'KeyL', width: 40, height: 40 },
      { label: ';', code: 'Semicolon', width: 40, height: 40 },
      { label: "'", code: 'Quote', width: 40, height: 40 },
      { label: 'Enter', code: 'Enter', width: 80, height: 40 },
      { label: '4', code: 'Numpad4', width: 40, height: 40 },
      { label: '5', code: 'Numpad5', width: 40, height: 40 },
      { label: '6', code: 'Numpad6', width: 40, height: 40 },
    ],
    [
      { label: 'Shift', code: 'ShiftLeft', width: 100, height: 40 },
      { label: 'Z', code: 'KeyZ', width: 40, height: 40 },
      { label: 'X', code: 'KeyX', width: 40, height: 40 },
      { label: 'C', code: 'KeyC', width: 40, height: 40 },
      { label: 'V', code: 'KeyV', width: 40, height: 40 },
      { label: 'B', code: 'KeyB', width: 40, height: 40 },
      { label: 'N', code: 'KeyN', width: 40, height: 40 },
      { label: 'M', code: 'KeyM', width: 40, height: 40 },
      { label: ',', code: 'Comma', width: 40, height: 40 },
      { label: '.', code: 'Period', width: 40, height: 40 },
      { label: '/', code: 'Slash', width: 40, height: 40 },
      { label: 'Shift', code: 'ShiftRight', width: 100, height: 40 },
      { label: '1', code: 'Numpad1', width: 40, height: 40 },
      { label: '2', code: 'Numpad2', width: 40, height: 40 },
      { label: '3', code: 'Numpad3', width: 40, height: 40 },
      { label: 'Enter', code: 'NumpadEnter', width: 40, height: 80 },
    ],
    [
      { label: 'Ctrl', code: 'ControlLeft', width: 60, height: 40 },
      { label: 'Win', code: 'MetaLeft', width: 60, height: 40 },
      { label: 'Alt', code: 'AltLeft', width: 60, height: 40 },
      { label: 'Space', code: 'Space', width: 300, height: 40 },
      { label: 'Alt', code: 'AltRight', width: 60, height: 40 },
      { label: 'Fn', code: 'Fn', width: 60, height: 40 },
      { label: 'Ctrl', code: 'ControlRight', width: 60, height: 40 },
      { label: '0', code: 'Numpad0', width: 80, height: 40 },
      { label: '.', code: 'NumpadDecimal', width: 40, height: 40 },
    ],
  ],
}

const compact96: KeybLayout = {
  name: '96%/90%',
  rows: [
    // Function keys row
    [
      { label: 'Esc', code: 'Escape', width: 40, color: 'orange' },
      { label: 'F1', code: 'F1', width: 40 },
      { label: 'F2', code: 'F2', width: 40 },
      { label: 'F3', code: 'F3', width: 40 },
      { label: 'F4', code: 'F4', width: 40 },
      { label: 'F5', code: 'F5', width: 40 },
      { label: 'F6', code: 'F6', width: 40 },
      { label: 'F7', code: 'F7', width: 40 },
      { label: 'F8', code: 'F8', width: 40 },
      { label: 'F9', code: 'F9', width: 40 },
      { label: 'F10', code: 'F10', width: 40 },
      { label: 'F11', code: 'F11', width: 40 },
      { label: 'F12', code: 'F12', width: 40 },
      { label: 'Del', code: 'Delete', width: 40 },
    ],
    // Number row
    [
      { label: '`', code: 'Backquote', width: 40 },
      { label: '1', code: 'Digit1', width: 40 },
      { label: '2', code: 'Digit2', width: 40 },
      { label: '3', code: 'Digit3', width: 40 },
      { label: '4', code: 'Digit4', width: 40 },
      { label: '5', code: 'Digit5', width: 40 },
      { label: '6', code: 'Digit6', width: 40 },
      { label: '7', code: 'Digit7', width: 40 },
      { label: '8', code: 'Digit8', width: 40 },
      { label: '9', code: 'Digit9', width: 40 },
      { label: '0', code: 'Digit0', width: 40 },
      { label: '-', code: 'Minus', width: 40 },
      { label: '=', code: 'Equal', width: 40 },
      { label: 'Backspace', code: 'Backspace', width: 80 },
      { label: 'Num', code: 'NumLock', width: 40 },
      { label: '/', code: 'NumpadDivide', width: 40 },
      { label: '*', code: 'NumpadMultiply', width: 40 },
      { label: '-', code: 'NumpadSubtract', width: 40 },
    ],
    // QWERTY row
    [
      { label: 'Tab', code: 'Tab', width: 60 },
      { label: 'Q', code: 'KeyQ', width: 40 },
      { label: 'W', code: 'KeyW', width: 40 },
      { label: 'E', code: 'KeyE', width: 40 },
      { label: 'R', code: 'KeyR', width: 40 },
      { label: 'T', code: 'KeyT', width: 40 },
      { label: 'Y', code: 'KeyY', width: 40 },
      { label: 'U', code: 'KeyU', width: 40 },
      { label: 'I', code: 'KeyI', width: 40 },
      { label: 'O', code: 'KeyO', width: 40 },
      { label: 'P', code: 'KeyP', width: 40 },
      { label: '[', code: 'BracketLeft', width: 40 },
      { label: ']', code: 'BracketRight', width: 40 },
      { label: '\\', code: 'Backslash', width: 60 },
      { label: '7', code: 'Numpad7', width: 40 },
      { label: '8', code: 'Numpad8', width: 40 },
      { label: '9', code: 'Numpad9', width: 40 },
      { label: '+', code: 'NumpadAdd', width: 40, height: 84 },
    ],
    // Home row
    [
      { label: 'Caps', code: 'CapsLock', width: 80 },
      { label: 'A', code: 'KeyA', width: 40 },
      { label: 'S', code: 'KeyS', width: 40 },
      { label: 'D', code: 'KeyD', width: 40 },
      { label: 'F', code: 'KeyF', width: 40 },
      { label: 'G', code: 'KeyG', width: 40 },
      { label: 'H', code: 'KeyH', width: 40 },
      { label: 'J', code: 'KeyJ', width: 40 },
      { label: 'K', code: 'KeyK', width: 40 },
      { label: 'L', code: 'KeyL', width: 40 },
      { label: ';', code: 'Semicolon', width: 40 },
      { label: "'", code: 'Quote', width: 40 },
      { label: 'Enter', code: 'Enter', width: 100 },
      { label: '4', code: 'Numpad4', width: 40 },
      { label: '5', code: 'Numpad5', width: 40 },
      { label: '6', code: 'Numpad6', width: 40 },
    ],
    // Shift row
    [
      { label: 'Shift', code: 'ShiftLeft', width: 100 },
      { label: 'Z', code: 'KeyZ', width: 40 },
      { label: 'X', code: 'KeyX', width: 40 },
      { label: 'C', code: 'KeyC', width: 40 },
      { label: 'V', code: 'KeyV', width: 40 },
      { label: 'B', code: 'KeyB', width: 40 },
      { label: 'N', code: 'KeyN', width: 40 },
      { label: 'M', code: 'KeyM', width: 40 },
      { label: ',', code: 'Comma', width: 40 },
      { label: '.', code: 'Period', width: 40 },
      { label: '/', code: 'Slash', width: 40 },
      { label: 'Shift', code: 'ShiftRight', width: 100 },
      { label: '1', code: 'Numpad1', width: 40 },
      { label: '2', code: 'Numpad2', width: 40 },
      { label: '3', code: 'Numpad3', width: 40 },
      { label: 'Enter', code: 'NumpadEnter', width: 40, height: 84 },
    ],
    // Bottom row
    [
      { label: 'Ctrl', code: 'ControlLeft', width: 60 },
      { label: 'Win', code: 'MetaLeft', width: 60 },
      { label: 'Alt', code: 'AltLeft', width: 60 },
      { label: 'Space', code: 'Space', width: 240 },
      { label: 'Alt', code: 'AltRight', width: 60 },
      { label: 'Fn', code: 'Fn', width: 60 },
      { label: 'Ctrl', code: 'ControlRight', width: 60 },
      { label: '0', code: 'Numpad0', width: 80 },
      { label: '.', code: 'NumpadDecimal', width: 40 },
    ],
  ],
}

const tkl: KeybLayout = {
  name: '80% TKL',
  rows: [
    // Function keys row
    [
      { label: 'Esc', code: 'Escape', width: 40, color: 'orange' },
      { label: 'F1', code: 'F1', width: 40 },
      { label: 'F2', code: 'F2', width: 40 },
      { label: 'F3', code: 'F3', width: 40 },
      { label: 'F4', code: 'F4', width: 40 },
      { label: 'F5', code: 'F5', width: 40 },
      { label: 'F6', code: 'F6', width: 40 },
      { label: 'F7', code: 'F7', width: 40 },
      { label: 'F8', code: 'F8', width: 40 },
      { label: 'F9', code: 'F9', width: 40 },
      { label: 'F10', code: 'F10', width: 40 },
      { label: 'F11', code: 'F11', width: 40 },
      { label: 'F12', code: 'F12', width: 40 },
      { label: 'PrtSc', code: 'PrintScreen', width: 40 },
      { label: 'ScrLk', code: 'ScrollLock', width: 40 },
      { label: 'Pause', code: 'Pause', width: 40 },
    ],
    // Number row
    [
      { label: '`', code: 'Backquote', width: 40 },
      { label: '1', code: 'Digit1', width: 40 },
      { label: '2', code: 'Digit2', width: 40 },
      { label: '3', code: 'Digit3', width: 40 },
      { label: '4', code: 'Digit4', width: 40 },
      { label: '5', code: 'Digit5', width: 40 },
      { label: '6', code: 'Digit6', width: 40 },
      { label: '7', code: 'Digit7', width: 40 },
      { label: '8', code: 'Digit8', width: 40 },
      { label: '9', code: 'Digit9', width: 40 },
      { label: '0', code: 'Digit0', width: 40 },
      { label: '-', code: 'Minus', width: 40 },
      { label: '=', code: 'Equal', width: 40 },
      { label: 'Backspace', code: 'Backspace', width: 80 },
      { label: 'Ins', code: 'Insert', width: 40 },
      { label: 'Home', code: 'Home', width: 40 },
      { label: 'PgUp', code: 'PageUp', width: 40 },
    ],
    // QWERTY row
    [
      { label: 'Tab', code: 'Tab', width: 60 },
      { label: 'Q', code: 'KeyQ', width: 40 },
      { label: 'W', code: 'KeyW', width: 40 },
      { label: 'E', code: 'KeyE', width: 40 },
      { label: 'R', code: 'KeyR', width: 40 },
      { label: 'T', code: 'KeyT', width: 40 },
      { label: 'Y', code: 'KeyY', width: 40 },
      { label: 'U', code: 'KeyU', width: 40 },
      { label: 'I', code: 'KeyI', width: 40 },
      { label: 'O', code: 'KeyO', width: 40 },
      { label: 'P', code: 'KeyP', width: 40 },
      { label: '[', code: 'BracketLeft', width: 40 },
      { label: ']', code: 'BracketRight', width: 40 },
      { label: '\\', code: 'Backslash', width: 60 },
      { label: 'Del', code: 'Delete', width: 40 },
      { label: 'End', code: 'End', width: 40 },
      { label: 'PgDn', code: 'PageDown', width: 40 },
    ],
    // Home row
    [
      { label: 'Caps', code: 'CapsLock', width: 80 },
      { label: 'A', code: 'KeyA', width: 40 },
      { label: 'S', code: 'KeyS', width: 40 },
      { label: 'D', code: 'KeyD', width: 40 },
      { label: 'F', code: 'KeyF', width: 40 },
      { label: 'G', code: 'KeyG', width: 40 },
      { label: 'H', code: 'KeyH', width: 40 },
      { label: 'J', code: 'KeyJ', width: 40 },
      { label: 'K', code: 'KeyK', width: 40 },
      { label: 'L', code: 'KeyL', width: 40 },
      { label: ';', code: 'Semicolon', width: 40 },
      { label: "'", code: 'Quote', width: 40 },
      { label: 'Enter', code: 'Enter', width: 100 },
    ],
    // Shift row
    [
      { label: 'Shift', code: 'ShiftLeft', width: 100 },
      { label: 'Z', code: 'KeyZ', width: 40 },
      { label: 'X', code: 'KeyX', width: 40 },
      { label: 'C', code: 'KeyC', width: 40 },
      { label: 'V', code: 'KeyV', width: 40 },
      { label: 'B', code: 'KeyB', width: 40 },
      { label: 'N', code: 'KeyN', width: 40 },
      { label: 'M', code: 'KeyM', width: 40 },
      { label: ',', code: 'Comma', width: 40 },
      { label: '.', code: 'Period', width: 40 },
      { label: '/', code: 'Slash', width: 40 },
      { label: 'Shift', code: 'ShiftRight', width: 100 },
      { label: '↑', code: 'ArrowUp', width: 40 },
    ],
    // Bottom row
    [
      { label: 'Ctrl', code: 'ControlLeft', width: 60 },
      { label: 'Win', code: 'MetaLeft', width: 60 },
      { label: 'Alt', code: 'AltLeft', width: 60 },
      { label: 'Space', code: 'Space', width: 260 },
      { label: 'Alt', code: 'AltRight', width: 60 },
      { label: 'Fn', code: 'Fn', width: 60 },
      { label: 'Ctrl', code: 'ControlRight', width: 60 },
      { label: '←', code: 'ArrowLeft', width: 40 },
      { label: '↓', code: 'ArrowDown', width: 40 },
      { label: '→', code: 'ArrowRight', width: 40 },
    ],
  ],
}

const compact75: KeybLayout = {
  name: '75%',
  rows: [
    // Function keys row
    [
      { label: 'Esc', code: 'Escape', width: 40, color: 'orange' },
      { label: 'F1', code: 'F1', width: 40 },
      { label: 'F2', code: 'F2', width: 40 },
      { label: 'F3', code: 'F3', width: 40 },
      { label: 'F4', code: 'F4', width: 40 },
      { label: 'F5', code: 'F5', width: 40 },
      { label: 'F6', code: 'F6', width: 40 },
      { label: 'F7', code: 'F7', width: 40 },
      { label: 'F8', code: 'F8', width: 40 },
      { label: 'F9', code: 'F9', width: 40 },
      { label: 'F10', code: 'F10', width: 40 },
      { label: 'F11', code: 'F11', width: 40 },
      { label: 'F12', code: 'F12', width: 40 },
      { label: 'Del', code: 'Delete', width: 40 },
    ],
    // Number row
    [
      { label: '`', code: 'Backquote', width: 40 },
      { label: '1', code: 'Digit1', width: 40 },
      { label: '2', code: 'Digit2', width: 40 },
      { label: '3', code: 'Digit3', width: 40 },
      { label: '4', code: 'Digit4', width: 40 },
      { label: '5', code: 'Digit5', width: 40 },
      { label: '6', code: 'Digit6', width: 40 },
      { label: '7', code: 'Digit7', width: 40 },
      { label: '8', code: 'Digit8', width: 40 },
      { label: '9', code: 'Digit9', width: 40 },
      { label: '0', code: 'Digit0', width: 40 },
      { label: '-', code: 'Minus', width: 40 },
      { label: '=', code: 'Equal', width: 40 },
      { label: 'Backspace', code: 'Backspace', width: 80 },
      { label: 'Home', code: 'Home', width: 40 },
    ],
    // QWERTY row
    [
      { label: 'Tab', code: 'Tab', width: 60 },
      { label: 'Q', code: 'KeyQ', width: 40 },
      { label: 'W', code: 'KeyW', width: 40 },
      { label: 'E', code: 'KeyE', width: 40 },
      { label: 'R', code: 'KeyR', width: 40 },
      { label: 'T', code: 'KeyT', width: 40 },
      { label: 'Y', code: 'KeyY', width: 40 },
      { label: 'U', code: 'KeyU', width: 40 },
      { label: 'I', code: 'KeyI', width: 40 },
      { label: 'O', code: 'KeyO', width: 40 },
      { label: 'P', code: 'KeyP', width: 40 },
      { label: '[', code: 'BracketLeft', width: 40 },
      { label: ']', code: 'BracketRight', width: 40 },
      { label: '\\', code: 'Backslash', width: 60 },
      { label: 'PgUp', code: 'PageUp', width: 40 },
    ],
    // Home row
    [
      { label: 'Caps', code: 'CapsLock', width: 80 },
      { label: 'A', code: 'KeyA', width: 40 },
      { label: 'S', code: 'KeyS', width: 40 },
      { label: 'D', code: 'KeyD', width: 40 },
      { label: 'F', code: 'KeyF', width: 40 },
      { label: 'G', code: 'KeyG', width: 40 },
      { label: 'H', code: 'KeyH', width: 40 },
      { label: 'J', code: 'KeyJ', width: 40 },
      { label: 'K', code: 'KeyK', width: 40 },
      { label: 'L', code: 'KeyL', width: 40 },
      { label: ';', code: 'Semicolon', width: 40 },
      { label: "'", code: 'Quote', width: 40 },
      { label: 'Enter', code: 'Enter', width: 80 },
      { label: 'PgDn', code: 'PageDown', width: 40 },
    ],
    // Shift row
    [
      { label: 'Shift', code: 'ShiftLeft', width: 100 },
      { label: 'Z', code: 'KeyZ', width: 40 },
      { label: 'X', code: 'KeyX', width: 40 },
      { label: 'C', code: 'KeyC', width: 40 },
      { label: 'V', code: 'KeyV', width: 40 },
      { label: 'B', code: 'KeyB', width: 40 },
      { label: 'N', code: 'KeyN', width: 40 },
      { label: 'M', code: 'KeyM', width: 40 },
      { label: ',', code: 'Comma', width: 40 },
      { label: '.', code: 'Period', width: 40 },
      { label: '/', code: 'Slash', width: 40 },
      { label: 'Shift', code: 'ShiftRight', width: 60 },
      { label: '↑', code: 'ArrowUp', width: 40 },
      { label: 'End', code: 'End', width: 40 },
    ],
    // Bottom row
    [
      { label: 'Ctrl', code: 'ControlLeft', width: 60 },
      { label: 'Win', code: 'MetaLeft', width: 60 },
      { label: 'Alt', code: 'AltLeft', width: 60 },
      { label: 'Space', code: 'Space', width: 220 },
      { label: 'Alt', code: 'AltRight', width: 60 },
      { label: 'Fn', code: 'Fn', width: 60 },
      { label: 'Ctrl', code: 'ControlRight', width: 60 },
      { label: '←', code: 'ArrowLeft', width: 40 },
      { label: '↓', code: 'ArrowDown', width: 40 },
      { label: '→', code: 'ArrowRight', width: 40 },
    ],
  ],
}

const compact65: KeybLayout = {
  name: '65%',
  rows: [
    // Number row
    [
      { label: 'Esc', code: 'Escape', width: 40, color: 'orange' },
      { label: '1', code: 'Digit1', width: 40 },
      { label: '2', code: 'Digit2', width: 40 },
      { label: '3', code: 'Digit3', width: 40 },
      { label: '4', code: 'Digit4', width: 40 },
      { label: '5', code: 'Digit5', width: 40 },
      { label: '6', code: 'Digit6', width: 40 },
      { label: '7', code: 'Digit7', width: 40 },
      { label: '8', code: 'Digit8', width: 40 },
      { label: '9', code: 'Digit9', width: 40 },
      { label: '0', code: 'Digit0', width: 40 },
      { label: '-', code: 'Minus', width: 40 },
      { label: '=', code: 'Equal', width: 40 },
      { label: 'Backspace', code: 'Backspace', width: 80 },
      { label: 'Home', code: 'Home', width: 40 },
    ],
    // QWERTY row
    [
      { label: 'Tab', code: 'Tab', width: 60 },
      { label: 'Q', code: 'KeyQ', width: 40 },
      { label: 'W', code: 'KeyW', width: 40 },
      { label: 'E', code: 'KeyE', width: 40 },
      { label: 'R', code: 'KeyR', width: 40 },
      { label: 'T', code: 'KeyT', width: 40 },
      { label: 'Y', code: 'KeyY', width: 40 },
      { label: 'U', code: 'KeyU', width: 40 },
      { label: 'I', code: 'KeyI', width: 40 },
      { label: 'O', code: 'KeyO', width: 40 },
      { label: 'P', code: 'KeyP', width: 40 },
      { label: '[', code: 'BracketLeft', width: 40 },
      { label: ']', code: 'BracketRight', width: 40 },
      { label: '\\', code: 'Backslash', width: 60 },
      { label: 'PgUp', code: 'PageUp', width: 40 },
    ],
    // Home row
    [
      { label: 'Caps', code: 'CapsLock', width: 80 },
      { label: 'A', code: 'KeyA', width: 40 },
      { label: 'S', code: 'KeyS', width: 40 },
      { label: 'D', code: 'KeyD', width: 40 },
      { label: 'F', code: 'KeyF', width: 40 },
      { label: 'G', code: 'KeyG', width: 40 },
      { label: 'H', code: 'KeyH', width: 40 },
      { label: 'J', code: 'KeyJ', width: 40 },
      { label: 'K', code: 'KeyK', width: 40 },
      { label: 'L', code: 'KeyL', width: 40 },
      { label: ';', code: 'Semicolon', width: 40 },
      { label: "'", code: 'Quote', width: 40 },
      { label: 'Enter', code: 'Enter', width: 100 },
      { label: 'PgDn', code: 'PageDown', width: 40 },
    ],
    // Shift row
    [
      { label: 'Shift', code: 'ShiftLeft', width: 100 },
      { label: 'Z', code: 'KeyZ', width: 40 },
      { label: 'X', code: 'KeyX', width: 40 },
      { label: 'C', code: 'KeyC', width: 40 },
      { label: 'V', code: 'KeyV', width: 40 },
      { label: 'B', code: 'KeyB', width: 40 },
      { label: 'N', code: 'KeyN', width: 40 },
      { label: 'M', code: 'KeyM', width: 40 },
      { label: ',', code: 'Comma', width: 40 },
      { label: '.', code: 'Period', width: 40 },
      { label: '/', code: 'Slash', width: 40 },
      { label: 'Shift', code: 'ShiftRight', width: 80 },
      { label: '↑', code: 'ArrowUp', width: 40 },
      { label: 'End', code: 'End', width: 40 },
    ],
    // Bottom row
    [
      { label: 'Ctrl', code: 'ControlLeft', width: 60 },
      { label: 'Win', code: 'MetaLeft', width: 60 },
      { label: 'Alt', code: 'AltLeft', width: 60 },
      { label: 'Space', code: 'Space', width: 240 },
      { label: 'Alt', code: 'AltRight', width: 60 },
      { label: 'Fn', code: 'Fn', width: 60 },
      { label: 'Ctrl', code: 'ControlRight', width: 60 },
      { label: '←', code: 'ArrowLeft', width: 40 },
      { label: '↓', code: 'ArrowDown', width: 40 },
      { label: '→', code: 'ArrowRight', width: 40 },
    ],
  ],
}

const compact60: KeybLayout = {
  name: '60%',
  rows: [
    // Number row
    [
      { label: 'Esc', code: 'Escape', width: 40, color: 'orange' },
      { label: '1', code: 'Digit1', width: 40 },
      { label: '2', code: 'Digit2', width: 40 },
      { label: '3', code: 'Digit3', width: 40 },
      { label: '4', code: 'Digit4', width: 40 },
      { label: '5', code: 'Digit5', width: 40 },
      { label: '6', code: 'Digit6', width: 40 },
      { label: '7', code: 'Digit7', width: 40 },
      { label: '8', code: 'Digit8', width: 40 },
      { label: '9', code: 'Digit9', width: 40 },
      { label: '0', code: 'Digit0', width: 40 },
      { label: '-', code: 'Minus', width: 40 },
      { label: '=', code: 'Equal', width: 40 },
      { label: 'Backspace', code: 'Backspace', width: 80 },
    ],
    // QWERTY row
    [
      { label: 'Tab', code: 'Tab', width: 60 },
      { label: 'Q', code: 'KeyQ', width: 40 },
      { label: 'W', code: 'KeyW', width: 40 },
      { label: 'E', code: 'KeyE', width: 40 },
      { label: 'R', code: 'KeyR', width: 40 },
      { label: 'T', code: 'KeyT', width: 40 },
      { label: 'Y', code: 'KeyY', width: 40 },
      { label: 'U', code: 'KeyU', width: 40 },
      { label: 'I', code: 'KeyI', width: 40 },
      { label: 'O', code: 'KeyO', width: 40 },
      { label: 'P', code: 'KeyP', width: 40 },
      { label: '[', code: 'BracketLeft', width: 40 },
      { label: ']', code: 'BracketRight', width: 40 },
      { label: '\\', code: 'Backslash', width: 60 },
    ],
    // Home row
    [
      { label: 'Caps', code: 'CapsLock', width: 80 },
      { label: 'A', code: 'KeyA', width: 40 },
      { label: 'S', code: 'KeyS', width: 40 },
      { label: 'D', code: 'KeyD', width: 40 },
      { label: 'F', code: 'KeyF', width: 40 },
      { label: 'G', code: 'KeyG', width: 40 },
      { label: 'H', code: 'KeyH', width: 40 },
      { label: 'J', code: 'KeyJ', width: 40 },
      { label: 'K', code: 'KeyK', width: 40 },
      { label: 'L', code: 'KeyL', width: 40 },
      { label: ';', code: 'Semicolon', width: 40 },
      { label: "'", code: 'Quote', width: 40 },
      { label: 'Enter', code: 'Enter', width: 60 },
    ],
    // Shift row
    [
      { label: 'Shift', code: 'ShiftLeft', width: 100 },
      { label: 'Z', code: 'KeyZ', width: 40 },
      { label: 'X', code: 'KeyX', width: 40 },
      { label: 'C', code: 'KeyC', width: 40 },
      { label: 'V', code: 'KeyV', width: 40 },
      { label: 'B', code: 'KeyB', width: 40 },
      { label: 'N', code: 'KeyN', width: 40 },
      { label: 'M', code: 'KeyM', width: 40 },
      { label: ',', code: 'Comma', width: 40 },
      { label: '.', code: 'Period', width: 40 },
      { label: '/', code: 'Slash', width: 40 },
      { label: 'Shift', code: 'ShiftRight', width: 120 },
    ],
    // Bottom row
    [
      { label: 'Ctrl', code: 'ControlLeft', width: 60 },
      { label: 'Win', code: 'MetaLeft', width: 60 },
      { label: 'Alt', code: 'AltLeft', width: 60 },
      { label: 'Space', code: 'Space', width: 260 },
      { label: 'Alt', code: 'AltRight', width: 60 },
      { label: 'Fn', code: 'Fn', width: 60 },
      { label: 'Ctrl', code: 'ControlRight', width: 60 },
    ],
  ],
}

export const layouts = {
  fullSize,
  compact1800,
  compact96,
  tkl,
  compact75,
  compact65,
  compact60,
}